# experiment details
name: "test_experiment"
project: "test_project"
use_wandb: False

# run details
n_replications: 2
epochs: 100
use_features: True
ensemble_size: 1

# dataset
dataset_type: dataset
folder_path: "eas/eas_dataset"
simulation_type: "index_feature"

# split
train_subset: 1.0
ood_subset: 1.0
split_type: random
transductive: True
clustering_method: Butina
min_cluster_size: 2
n_ood_test_compounds: 100
