name: test_experiment
project: ani-cxx
use_wandb: True
n_devices: 1

dataset_path: ./data/ani-cxx/experiment_2/dataset.db
models_path: ./data/ani-cxx/experiment_2/models/
split_file_path: ./data/ani-cxx/experiment_2/splits/cc_5_dft_30_ood.npz
has_virtual_reactions: False
n_simulations: 1

epochs: 100
n_replications: 3
lr: 0.001
batch_size: 32
cutoff: 5.0
n_radial: 32
n_atom_basis: 32
n_interactions: 3
sim_embedding_dim: 8